# Generated by Django 5.0.2 on 2024-03-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScmsUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_username", models.CharField(max_length=255)),
                ("u_password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "scms_user",
            },
        ),
        migrations.CreateModel(
            name="ScmsComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_in_image", models.FileField(upload_to="images/")),
                ("c_verified", models.CharField(default="n", max_length=1)),
                ("c_resolved", models.CharField(default="n", max_length=1)),
                ("c_lat", models.FloatField()),
                ("c_long", models.FloatField()),
                ("c_class", models.JSONField(default=list)),
                ("c_out_image", models.FileField(null=True, upload_to="images/")),
                ("c_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.scmsuser"
                    ),
                ),
            ],
            options={
                "db_table": "scms_complaint",
            },
        ),
    ]
