# Generated by Django 5.0.2 on 2024-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_scmsuser_u_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="scmscomplaint",
            name="c_title",
            field=models.CharField(default="complaint", max_length=255),
            preserve_default=False,
        ),
    ]
