# Generated by Django 5.0.2 on 2024-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_scmscomplaint_c_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="scmsuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
