# Generated by Django 5.0.2 on 2024-03-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_scmsuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="scmscomplaint",
            name="resolver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolved_complaints",
                to="main.scmsuser",
            ),
        ),
        migrations.AddField(
            model_name="scmscomplaint",
            name="verifier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verified_complaints",
                to="main.scmsuser",
            ),
        ),
    ]
